general.import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
dynamic_padding = true
# decorations = "None"
opacity = 0.9
blur = true

[selection]
save_to_clipboard = true

[mouse]
bindings = [
	{ mouse = "Middle", action = "SpawnNewInstance" }
]
# hide_when_typing = true

[scrolling]
history = 69420

[keyboard]
bindings = [
	{ key = "N", mods = "Control|Shift", action = "SpawnNewInstance" }
]
